# Dataset
dataset_root: ${oc.env:HOME}/Datasets/OpenEQA/scannet/
dataset_config: conceptgraph/dataset/dataconfigs/scannet/openeqa_clip.yaml
scene_id: null
start: 0
end: -1
stride: 5
image_height: null
image_width: null

# Input detections
gsa_variant: ram_withbg_allclasses
detection_folder_name: gsa_detections_${gsa_variant}
det_vis_folder_name: gsa_vis_${gsa_variant}
color_file_name: gsa_classes_${gsa_variant}

device: cuda

use_iou: true
spatial_sim_type: overlap
phys_bias: 0.0
match_method: sim_sum
semantic_threshold: 0.5
physical_threshold: 0.5
sim_threshold: 1.2

use_contain_number: false
contain_area_thresh: 0.95
contain_mismatch_penalty: 0.5

mask_area_threshold: 25
mask_conf_threshold: 0.25
max_bbox_area_ratio: 0.5
skip_bg: true
min_points_threshold: 16

downsample_voxel_size: 0.025
dbscan_remove_noise: true
dbscan_eps: 0.1
dbscan_min_points: 10

obj_min_points: 0
obj_min_detections: 3

merge_overlap_thresh: 0.7
merge_visual_sim_thresh: 0.8
merge_text_sim_thresh: 0.8

denoise_interval: 20
filter_interval: -1
merge_interval: 20

save_pcd: true
save_suffix: exp

vis_render: false
debug_render: false
class_agnostic: true

save_objects_all_frames: false
render_camera_path: "replica_room0.json"
