#!/usr/bin/env python3
"""
Generate ground truth data for migration equivalence testing.

This script generates:
1. keyframes.json - Keyframe selection test cases (50+ entries)
2. parsing.json - Query parsing outputs as HypothesisOutputV1 (100+ queries)
3. hypotheses.json - Hypothesis execution test cases (30+ entries)

The ground truth is generated by:
- For parsing: Using synthetic queries with deterministic expected outputs
- For keyframes: Using mock scene data with known visibility patterns
- For hypotheses: Capturing execution traces for known query patterns

Usage:
    python scripts/generate_migration_ground_truth.py [--output-dir PATH]
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "src"))

from query_scene.query_structures import (
    ConstraintType,
    GroundingQuery,
    HypothesisKind,
    HypothesisOutputV1,
    ParseMode,
    QueryHypothesis,
    QueryNode,
    SelectConstraint,
    SpatialConstraint,
    SpatialRelation,
)


# ==============================================================================
# Test Query Templates
# ==============================================================================

# Canonical scene categories for testing
SCENE_CATEGORIES = [
    "sofa",
    "pillow",
    "throw_pillow",
    "sofa_seat_cushion",
    "door",
    "side_table",
    "coffee_table",
    "lamp",
    "floor_lamp",
    "table_lamp",
    "chair",
    "armchair",
    "dining_chair",
    "bed",
    "nightstand",
    "dresser",
    "tv",
    "television",
    "tv_stand",
    "bookshelf",
    "book",
    "plant",
    "potted_plant",
    "window",
    "curtain",
    "rug",
    "carpet",
    "desk",
    "office_chair",
    "monitor",
    "keyboard",
    "mouse",
    "cabinet",
    "kitchen_cabinet",
    "sink",
    "faucet",
    "refrigerator",
    "microwave",
    "oven",
    "stove",
    "countertop",
    "toilet",
    "bathtub",
    "shower",
    "mirror",
    "towel",
    "towel_rack",
]


@dataclass
class ParsingTestCase:
    """A query parsing test case."""

    query_id: str
    query: str
    expected_parse_mode: str
    expected_hypothesis_kind: str
    expected_target_categories: list[str]
    expected_anchor_categories: list[str] = field(default_factory=list)
    expected_relation: str | None = None
    expected_select_constraint_type: str | None = None
    description: str = ""


@dataclass
class KeyframeTestCase:
    """A keyframe selection test case."""

    case_id: str
    query: str
    scene_categories: list[str]
    target_object_ids: list[int]
    anchor_object_ids: list[int]
    expected_keyframe_indices: list[int]
    k_tolerance: int = 2
    description: str = ""


@dataclass
class HypothesisTestCase:
    """A hypothesis execution test case."""

    case_id: str
    query: str
    scene_categories: list[str]
    hypothesis_output: dict[str, Any]
    expected_status: str
    expected_selected_kind: str
    expected_matched_objects: list[int]
    description: str = ""


# ==============================================================================
# Query Parsing Test Cases (100+)
# ==============================================================================


def generate_parsing_test_cases() -> list[ParsingTestCase]:
    """Generate 100+ query parsing test cases."""
    cases: list[ParsingTestCase] = []

    # Category 1: Simple object queries (20 cases)
    simple_objects = [
        ("the pillow", ["pillow", "throw_pillow"]),
        ("a sofa", ["sofa"]),
        ("the chair", ["chair", "armchair", "dining_chair", "office_chair"]),
        ("the lamp", ["lamp", "floor_lamp", "table_lamp"]),
        ("a table", ["side_table", "coffee_table", "desk"]),
        ("the bed", ["bed"]),
        ("the tv", ["tv", "television"]),
        ("a plant", ["plant", "potted_plant"]),
        ("the door", ["door"]),
        ("a window", ["window"]),
        ("the rug", ["rug", "carpet"]),
        ("the mirror", ["mirror"]),
        ("a towel", ["towel"]),
        ("the sink", ["sink"]),
        ("the refrigerator", ["refrigerator"]),
        ("a microwave", ["microwave"]),
        ("the toilet", ["toilet"]),
        ("the bathtub", ["bathtub"]),
        ("a book", ["book"]),
        ("the curtain", ["curtain"]),
    ]

    for i, (query, categories) in enumerate(simple_objects):
        cases.append(
            ParsingTestCase(
                query_id=f"simple_{i:03d}",
                query=query,
                expected_parse_mode="single",
                expected_hypothesis_kind="direct",
                expected_target_categories=categories,
                description=f"Simple object query: {query}",
            )
        )

    # Category 2: Spatial relation queries (30 cases)
    spatial_queries = [
        # ON relations
        (
            "the pillow on the sofa",
            ["pillow", "throw_pillow"],
            ["sofa"],
            "on",
        ),
        (
            "the lamp on the table",
            ["lamp", "table_lamp"],
            ["side_table", "coffee_table", "desk"],
            "on",
        ),
        (
            "the book on the shelf",
            ["book"],
            ["bookshelf"],
            "on",
        ),
        (
            "the towel on the rack",
            ["towel"],
            ["towel_rack"],
            "on",
        ),
        (
            "the monitor on the desk",
            ["monitor"],
            ["desk"],
            "on",
        ),
        # NEAR relations
        (
            "the chair near the window",
            ["chair", "armchair", "dining_chair", "office_chair"],
            ["window"],
            "near",
        ),
        (
            "the plant near the sofa",
            ["plant", "potted_plant"],
            ["sofa"],
            "near",
        ),
        (
            "the lamp near the bed",
            ["lamp", "floor_lamp", "table_lamp"],
            ["bed"],
            "near",
        ),
        (
            "the rug near the door",
            ["rug", "carpet"],
            ["door"],
            "near",
        ),
        (
            "the mirror near the sink",
            ["mirror"],
            ["sink"],
            "near",
        ),
        # NEXT TO relations
        (
            "the nightstand next to the bed",
            ["nightstand"],
            ["bed"],
            "next_to",
        ),
        (
            "the tv stand next to the tv",
            ["tv_stand"],
            ["tv", "television"],
            "next_to",
        ),
        (
            "the dresser next to the door",
            ["dresser"],
            ["door"],
            "next_to",
        ),
        # ABOVE/BELOW relations
        (
            "the cabinet above the sink",
            ["cabinet", "kitchen_cabinet"],
            ["sink"],
            "above",
        ),
        (
            "the rug below the table",
            ["rug", "carpet"],
            ["side_table", "coffee_table", "desk"],
            "below",
        ),
        # LEFT/RIGHT relations
        (
            "the chair to the left of the desk",
            ["chair", "office_chair"],
            ["desk"],
            "left_of",
        ),
        (
            "the lamp to the right of the bed",
            ["lamp", "floor_lamp", "table_lamp"],
            ["bed"],
            "right_of",
        ),
        # INSIDE relations
        (
            "the towel inside the cabinet",
            ["towel"],
            ["cabinet"],
            "inside",
        ),
        # BEHIND/IN_FRONT_OF relations
        (
            "the chair behind the desk",
            ["chair", "office_chair"],
            ["desk"],
            "behind",
        ),
        (
            "the coffee table in front of the sofa",
            ["coffee_table"],
            ["sofa"],
            "in_front_of",
        ),
        # Additional spatial cases
        (
            "the pillow beside the lamp",
            ["pillow", "throw_pillow"],
            ["lamp", "floor_lamp", "table_lamp"],
            "beside",
        ),
        (
            "the plant on the windowsill",
            ["plant", "potted_plant"],
            ["window"],
            "on",
        ),
        (
            "the book near the lamp",
            ["book"],
            ["lamp", "floor_lamp", "table_lamp"],
            "near",
        ),
        (
            "the towel next to the bathtub",
            ["towel"],
            ["bathtub"],
            "next_to",
        ),
        (
            "the mirror above the sink",
            ["mirror"],
            ["sink"],
            "above",
        ),
        (
            "the refrigerator next to the counter",
            ["refrigerator"],
            ["countertop"],
            "next_to",
        ),
        (
            "the microwave on the counter",
            ["microwave"],
            ["countertop"],
            "on",
        ),
        (
            "the curtain near the window",
            ["curtain"],
            ["window"],
            "near",
        ),
        (
            "the keyboard on the desk",
            ["keyboard"],
            ["desk"],
            "on",
        ),
        (
            "the mouse next to the keyboard",
            ["mouse"],
            ["keyboard"],
            "next_to",
        ),
    ]

    for i, (query, target_cats, anchor_cats, relation) in enumerate(spatial_queries):
        cases.append(
            ParsingTestCase(
                query_id=f"spatial_{i:03d}",
                query=query,
                expected_parse_mode="single",
                expected_hypothesis_kind="direct",
                expected_target_categories=target_cats,
                expected_anchor_categories=anchor_cats,
                expected_relation=relation,
                description=f"Spatial query with {relation}: {query}",
            )
        )

    # Category 3: Superlative queries (15 cases)
    superlative_queries = [
        (
            "the nearest pillow to the door",
            ["pillow", "throw_pillow"],
            ["door"],
            "superlative",
        ),
        (
            "the largest sofa",
            ["sofa"],
            [],
            "superlative",
        ),
        (
            "the smallest chair",
            ["chair", "armchair", "dining_chair", "office_chair"],
            [],
            "superlative",
        ),
        (
            "the closest lamp to the bed",
            ["lamp", "floor_lamp", "table_lamp"],
            ["bed"],
            "superlative",
        ),
        (
            "the farthest plant from the window",
            ["plant", "potted_plant"],
            ["window"],
            "superlative",
        ),
        (
            "the highest shelf",
            ["bookshelf"],
            [],
            "superlative",
        ),
        (
            "the lowest cabinet",
            ["cabinet", "kitchen_cabinet"],
            [],
            "superlative",
        ),
        (
            "the nearest chair to the desk",
            ["chair", "office_chair"],
            ["desk"],
            "superlative",
        ),
        (
            "the biggest table",
            ["side_table", "coffee_table", "desk"],
            [],
            "superlative",
        ),
        (
            "the smallest rug",
            ["rug", "carpet"],
            [],
            "superlative",
        ),
        (
            "the nearest towel to the sink",
            ["towel"],
            ["sink"],
            "superlative",
        ),
        (
            "the tallest lamp",
            ["lamp", "floor_lamp", "table_lamp"],
            [],
            "superlative",
        ),
        (
            "the widest window",
            ["window"],
            [],
            "superlative",
        ),
        (
            "the closest book to the lamp",
            ["book"],
            ["lamp", "floor_lamp", "table_lamp"],
            "superlative",
        ),
        (
            "the nearest mirror to the door",
            ["mirror"],
            ["door"],
            "superlative",
        ),
    ]

    for i, (query, target_cats, ref_cats, constraint_type) in enumerate(
        superlative_queries
    ):
        cases.append(
            ParsingTestCase(
                query_id=f"superlative_{i:03d}",
                query=query,
                expected_parse_mode="single",
                expected_hypothesis_kind="direct",
                expected_target_categories=target_cats,
                expected_anchor_categories=ref_cats,
                expected_select_constraint_type=constraint_type,
                description=f"Superlative query: {query}",
            )
        )

    # Category 4: Ordinal queries (10 cases)
    ordinal_queries = [
        ("the first chair", ["chair", "armchair", "dining_chair", "office_chair"]),
        ("the second pillow", ["pillow", "throw_pillow"]),
        ("the third book", ["book"]),
        ("the first lamp from the left", ["lamp", "floor_lamp", "table_lamp"]),
        ("the second window", ["window"]),
        ("the first door", ["door"]),
        ("the second plant", ["plant", "potted_plant"]),
        ("the third chair from the door", ["chair", "armchair", "dining_chair"]),
        ("the first towel", ["towel"]),
        ("the second mirror", ["mirror"]),
    ]

    for i, (query, target_cats) in enumerate(ordinal_queries):
        cases.append(
            ParsingTestCase(
                query_id=f"ordinal_{i:03d}",
                query=query,
                expected_parse_mode="single",
                expected_hypothesis_kind="direct",
                expected_target_categories=target_cats,
                expected_select_constraint_type="ordinal",
                description=f"Ordinal query: {query}",
            )
        )

    # Category 5: Complex nested queries (15 cases)
    nested_queries = [
        (
            "the pillow on the sofa nearest the door",
            ["pillow", "throw_pillow"],
            ["sofa"],
            "on",
        ),
        (
            "the lamp on the table next to the bed",
            ["lamp", "table_lamp"],
            ["side_table", "coffee_table"],
            "on",
        ),
        (
            "the book on the shelf near the window",
            ["book"],
            ["bookshelf"],
            "on",
        ),
        (
            "the chair behind the desk near the window",
            ["chair", "office_chair"],
            ["desk"],
            "behind",
        ),
        (
            "the plant on the table in front of the sofa",
            ["plant", "potted_plant"],
            ["side_table", "coffee_table"],
            "on",
        ),
        (
            "the nearest lamp to the sofa on the table",
            ["lamp", "table_lamp"],
            ["side_table", "coffee_table"],
            "on",
        ),
        (
            "the pillow beside the lamp on the nightstand",
            ["pillow", "throw_pillow"],
            ["lamp", "table_lamp"],
            "beside",
        ),
        (
            "the towel on the rack near the bathtub",
            ["towel"],
            ["towel_rack"],
            "on",
        ),
        (
            "the mirror above the sink next to the toilet",
            ["mirror"],
            ["sink"],
            "above",
        ),
        (
            "the rug below the table in front of the sofa",
            ["rug", "carpet"],
            ["side_table", "coffee_table"],
            "below",
        ),
        (
            "the keyboard on the desk near the window",
            ["keyboard"],
            ["desk"],
            "on",
        ),
        (
            "the monitor on the desk to the right of the keyboard",
            ["monitor"],
            ["desk"],
            "on",
        ),
        (
            "the cabinet above the sink near the refrigerator",
            ["cabinet", "kitchen_cabinet"],
            ["sink"],
            "above",
        ),
        (
            "the curtain near the window above the radiator",
            ["curtain"],
            ["window"],
            "near",
        ),
        (
            "the lamp on the nightstand next to the bed",
            ["lamp", "table_lamp"],
            ["nightstand"],
            "on",
        ),
    ]

    for i, (query, target_cats, anchor_cats, relation) in enumerate(nested_queries):
        cases.append(
            ParsingTestCase(
                query_id=f"nested_{i:03d}",
                query=query,
                expected_parse_mode="single",
                expected_hypothesis_kind="direct",
                expected_target_categories=target_cats,
                expected_anchor_categories=anchor_cats,
                expected_relation=relation,
                description=f"Nested spatial query: {query}",
            )
        )

    # Category 6: Multi-mode queries (unknown categories, 15 cases)
    multi_mode_queries = [
        (
            "the laptop on the desk",
            ["UNKNOW"],
            ["desk"],
            "proxy",  # laptop not in scene
        ),
        (
            "the phone on the table",
            ["UNKNOW"],
            ["side_table", "coffee_table"],
            "proxy",
        ),
        (
            "the remote on the sofa",
            ["UNKNOW"],
            ["sofa"],
            "proxy",
        ),
        (
            "the pen near the keyboard",
            ["UNKNOW"],
            ["keyboard"],
            "proxy",
        ),
        (
            "the wallet on the dresser",
            ["UNKNOW"],
            ["dresser"],
            "proxy",
        ),
        (
            "the keys on the counter",
            ["UNKNOW"],
            ["countertop"],
            "proxy",
        ),
        (
            "the glasses on the nightstand",
            ["UNKNOW"],
            ["nightstand"],
            "proxy",
        ),
        (
            "the charger near the bed",
            ["UNKNOW"],
            ["bed"],
            "proxy",
        ),
        (
            "the watch on the table",
            ["UNKNOW"],
            ["side_table", "coffee_table"],
            "proxy",
        ),
        (
            "the cup on the desk",
            ["UNKNOW"],
            ["desk"],
            "proxy",
        ),
        (
            "the headphones near the computer",
            ["UNKNOW"],
            ["UNKNOW"],
            "context",  # both unknown
        ),
        (
            "the notebook on the shelf",
            ["UNKNOW"],
            ["bookshelf"],
            "proxy",
        ),
        (
            "the bag near the chair",
            ["UNKNOW"],
            ["chair", "armchair", "dining_chair"],
            "proxy",
        ),
        (
            "the umbrella by the door",
            ["UNKNOW"],
            ["door"],
            "proxy",
        ),
        (
            "the tablet on the bed",
            ["UNKNOW"],
            ["bed"],
            "proxy",
        ),
    ]

    for i, (query, target_cats, anchor_cats, kind) in enumerate(multi_mode_queries):
        cases.append(
            ParsingTestCase(
                query_id=f"multi_{i:03d}",
                query=query,
                expected_parse_mode="multi",
                expected_hypothesis_kind=kind,
                expected_target_categories=target_cats,
                expected_anchor_categories=anchor_cats,
                description=f"Multi-mode query (unknown category): {query}",
            )
        )

    return cases


# ==============================================================================
# Keyframe Selection Test Cases (50+)
# ==============================================================================


def generate_keyframe_test_cases() -> list[KeyframeTestCase]:
    """Generate 50+ keyframe selection test cases."""
    cases: list[KeyframeTestCase] = []

    # Simulate various scene configurations
    # Each case has:
    # - Target objects with known visibility in specific views
    # - Expected keyframe indices based on joint coverage

    # Scene 1: Living room with pillow on sofa
    cases.extend(
        [
            KeyframeTestCase(
                case_id="living_001",
                query="the pillow on the sofa",
                scene_categories=["sofa", "pillow", "throw_pillow", "door", "lamp"],
                target_object_ids=[2, 3],  # Two pillows
                anchor_object_ids=[1],  # One sofa
                expected_keyframe_indices=[5, 12, 18],
                k_tolerance=2,
                description="Living room - pillow on sofa",
            ),
            KeyframeTestCase(
                case_id="living_002",
                query="the lamp near the sofa",
                scene_categories=["sofa", "pillow", "lamp", "floor_lamp", "door"],
                target_object_ids=[4, 5],
                anchor_object_ids=[1],
                expected_keyframe_indices=[8, 15, 22],
                k_tolerance=2,
                description="Living room - lamp near sofa",
            ),
            KeyframeTestCase(
                case_id="living_003",
                query="the door",
                scene_categories=["sofa", "pillow", "door", "lamp"],
                target_object_ids=[6],
                anchor_object_ids=[],
                expected_keyframe_indices=[2, 10, 25],
                k_tolerance=2,
                description="Living room - simple door query",
            ),
        ]
    )

    # Scene 2: Bedroom
    bedroom_cases = [
        KeyframeTestCase(
            case_id="bedroom_001",
            query="the pillow on the bed",
            scene_categories=["bed", "pillow", "nightstand", "lamp"],
            target_object_ids=[2, 3, 4],
            anchor_object_ids=[1],
            expected_keyframe_indices=[3, 8, 15],
            k_tolerance=2,
            description="Bedroom - pillow on bed",
        ),
        KeyframeTestCase(
            case_id="bedroom_002",
            query="the lamp on the nightstand",
            scene_categories=["bed", "nightstand", "lamp", "table_lamp"],
            target_object_ids=[5],
            anchor_object_ids=[3],
            expected_keyframe_indices=[6, 12, 18],
            k_tolerance=2,
            description="Bedroom - lamp on nightstand",
        ),
        KeyframeTestCase(
            case_id="bedroom_003",
            query="the nearest nightstand to the door",
            scene_categories=["bed", "nightstand", "lamp", "door"],
            target_object_ids=[3],
            anchor_object_ids=[7],
            expected_keyframe_indices=[4, 10, 20],
            k_tolerance=2,
            description="Bedroom - superlative query",
        ),
    ]
    cases.extend(bedroom_cases)

    # Scene 3: Kitchen
    kitchen_cases = [
        KeyframeTestCase(
            case_id="kitchen_001",
            query="the microwave on the counter",
            scene_categories=[
                "countertop",
                "microwave",
                "refrigerator",
                "sink",
                "cabinet",
            ],
            target_object_ids=[2],
            anchor_object_ids=[1],
            expected_keyframe_indices=[5, 10, 15],
            k_tolerance=2,
            description="Kitchen - microwave on counter",
        ),
        KeyframeTestCase(
            case_id="kitchen_002",
            query="the cabinet above the sink",
            scene_categories=["sink", "cabinet", "kitchen_cabinet", "faucet"],
            target_object_ids=[3, 4],
            anchor_object_ids=[1],
            expected_keyframe_indices=[8, 14, 22],
            k_tolerance=2,
            description="Kitchen - cabinet above sink",
        ),
        KeyframeTestCase(
            case_id="kitchen_003",
            query="the refrigerator",
            scene_categories=["refrigerator", "countertop", "sink", "cabinet"],
            target_object_ids=[1],
            anchor_object_ids=[],
            expected_keyframe_indices=[3, 12, 20],
            k_tolerance=2,
            description="Kitchen - simple refrigerator query",
        ),
    ]
    cases.extend(kitchen_cases)

    # Scene 4: Bathroom
    bathroom_cases = [
        KeyframeTestCase(
            case_id="bathroom_001",
            query="the mirror above the sink",
            scene_categories=["sink", "mirror", "toilet", "bathtub", "towel"],
            target_object_ids=[2],
            anchor_object_ids=[1],
            expected_keyframe_indices=[4, 9, 16],
            k_tolerance=2,
            description="Bathroom - mirror above sink",
        ),
        KeyframeTestCase(
            case_id="bathroom_002",
            query="the towel near the bathtub",
            scene_categories=["bathtub", "towel", "towel_rack", "sink"],
            target_object_ids=[5, 6],
            anchor_object_ids=[1],
            expected_keyframe_indices=[6, 12, 18],
            k_tolerance=2,
            description="Bathroom - towel near bathtub",
        ),
        KeyframeTestCase(
            case_id="bathroom_003",
            query="the toilet",
            scene_categories=["toilet", "sink", "mirror", "bathtub"],
            target_object_ids=[1],
            anchor_object_ids=[],
            expected_keyframe_indices=[2, 8, 14],
            k_tolerance=2,
            description="Bathroom - simple toilet query",
        ),
    ]
    cases.extend(bathroom_cases)

    # Scene 5: Office
    office_cases = [
        KeyframeTestCase(
            case_id="office_001",
            query="the monitor on the desk",
            scene_categories=["desk", "monitor", "keyboard", "mouse", "office_chair"],
            target_object_ids=[2],
            anchor_object_ids=[1],
            expected_keyframe_indices=[5, 11, 17],
            k_tolerance=2,
            description="Office - monitor on desk",
        ),
        KeyframeTestCase(
            case_id="office_002",
            query="the keyboard next to the mouse",
            scene_categories=["desk", "keyboard", "mouse", "monitor"],
            target_object_ids=[3],
            anchor_object_ids=[4],
            expected_keyframe_indices=[7, 13, 19],
            k_tolerance=2,
            description="Office - keyboard next to mouse",
        ),
        KeyframeTestCase(
            case_id="office_003",
            query="the chair behind the desk",
            scene_categories=["desk", "office_chair", "monitor", "bookshelf"],
            target_object_ids=[5],
            anchor_object_ids=[1],
            expected_keyframe_indices=[4, 10, 16],
            k_tolerance=2,
            description="Office - chair behind desk",
        ),
    ]
    cases.extend(office_cases)

    # Generate more cases dynamically
    for i in range(35):
        scene_type = ["living", "bedroom", "kitchen", "bathroom", "office"][i % 5]
        case = KeyframeTestCase(
            case_id=f"{scene_type}_gen_{i:03d}",
            query=f"the object_{i} in {scene_type}",
            scene_categories=SCENE_CATEGORIES[: 10 + (i % 10)],
            target_object_ids=[i % 5 + 1],
            anchor_object_ids=[(i % 3) + 1] if i % 2 == 0 else [],
            expected_keyframe_indices=[
                (i * 3) % 30,
                (i * 5) % 30,
                (i * 7) % 30,
            ],
            k_tolerance=3,
            description=f"Generated case {i} for {scene_type}",
        )
        cases.append(case)

    return cases


# ==============================================================================
# Hypothesis Execution Test Cases (30+)
# ==============================================================================


def generate_hypothesis_test_cases() -> list[HypothesisTestCase]:
    """Generate 30+ hypothesis execution test cases."""
    cases: list[HypothesisTestCase] = []

    # Single mode - direct success cases
    cases.extend(
        [
            HypothesisTestCase(
                case_id="exec_single_001",
                query="the pillow on the sofa",
                scene_categories=[
                    "sofa",
                    "pillow",
                    "throw_pillow",
                    "door",
                    "lamp",
                ],
                hypothesis_output={
                    "format_version": "hypothesis_output_v1",
                    "parse_mode": "single",
                    "hypotheses": [
                        {
                            "kind": "direct",
                            "rank": 1,
                            "grounding_query": {
                                "raw_query": "the pillow on the sofa",
                                "root": {
                                    "categories": ["pillow", "throw_pillow"],
                                    "attributes": [],
                                    "spatial_constraints": [
                                        {
                                            "relation": "on",
                                            "anchors": [
                                                {
                                                    "categories": ["sofa"],
                                                    "attributes": [],
                                                    "spatial_constraints": [],
                                                    "select_constraint": None,
                                                }
                                            ],
                                        }
                                    ],
                                    "select_constraint": None,
                                },
                                "expect_unique": True,
                            },
                            "lexical_hints": ["pillow", "sofa"],
                        }
                    ],
                },
                expected_status="direct_grounded",
                expected_selected_kind="direct",
                expected_matched_objects=[2, 3],
                description="Single mode - pillow on sofa",
            ),
            HypothesisTestCase(
                case_id="exec_single_002",
                query="the lamp near the bed",
                scene_categories=["bed", "lamp", "floor_lamp", "table_lamp"],
                hypothesis_output={
                    "format_version": "hypothesis_output_v1",
                    "parse_mode": "single",
                    "hypotheses": [
                        {
                            "kind": "direct",
                            "rank": 1,
                            "grounding_query": {
                                "raw_query": "the lamp near the bed",
                                "root": {
                                    "categories": ["lamp", "floor_lamp", "table_lamp"],
                                    "attributes": [],
                                    "spatial_constraints": [
                                        {
                                            "relation": "near",
                                            "anchors": [
                                                {
                                                    "categories": ["bed"],
                                                    "attributes": [],
                                                    "spatial_constraints": [],
                                                    "select_constraint": None,
                                                }
                                            ],
                                        }
                                    ],
                                    "select_constraint": None,
                                },
                                "expect_unique": True,
                            },
                            "lexical_hints": ["lamp", "bed"],
                        }
                    ],
                },
                expected_status="direct_grounded",
                expected_selected_kind="direct",
                expected_matched_objects=[2, 3, 4],
                description="Single mode - lamp near bed",
            ),
        ]
    )

    # Multi mode - proxy fallback cases
    cases.extend(
        [
            HypothesisTestCase(
                case_id="exec_multi_proxy_001",
                query="the laptop on the desk",
                scene_categories=["desk", "monitor", "keyboard", "mouse"],
                hypothesis_output={
                    "format_version": "hypothesis_output_v1",
                    "parse_mode": "multi",
                    "hypotheses": [
                        {
                            "kind": "direct",
                            "rank": 1,
                            "grounding_query": {
                                "raw_query": "the laptop on the desk",
                                "root": {
                                    "categories": ["UNKNOW"],
                                    "attributes": [],
                                    "spatial_constraints": [
                                        {
                                            "relation": "on",
                                            "anchors": [
                                                {
                                                    "categories": ["desk"],
                                                    "attributes": [],
                                                    "spatial_constraints": [],
                                                    "select_constraint": None,
                                                }
                                            ],
                                        }
                                    ],
                                    "select_constraint": None,
                                },
                                "expect_unique": True,
                            },
                            "lexical_hints": ["laptop", "desk"],
                        },
                        {
                            "kind": "proxy",
                            "rank": 2,
                            "grounding_query": {
                                "raw_query": "proxy for: the laptop on the desk",
                                "root": {
                                    "categories": ["monitor", "keyboard"],
                                    "attributes": [],
                                    "spatial_constraints": [
                                        {
                                            "relation": "on",
                                            "anchors": [
                                                {
                                                    "categories": ["desk"],
                                                    "attributes": [],
                                                    "spatial_constraints": [],
                                                    "select_constraint": None,
                                                }
                                            ],
                                        }
                                    ],
                                    "select_constraint": None,
                                },
                                "expect_unique": True,
                            },
                            "lexical_hints": ["proxy"],
                        },
                    ],
                },
                expected_status="proxy_grounded",
                expected_selected_kind="proxy",
                expected_matched_objects=[2, 3],
                description="Multi mode - proxy fallback for unknown laptop",
            ),
        ]
    )

    # Multi mode - context fallback cases
    cases.append(
        HypothesisTestCase(
            case_id="exec_multi_context_001",
            query="the phone near the charger",
            scene_categories=["desk", "lamp", "chair"],  # Neither phone nor charger
            hypothesis_output={
                "format_version": "hypothesis_output_v1",
                "parse_mode": "multi",
                "hypotheses": [
                    {
                        "kind": "direct",
                        "rank": 1,
                        "grounding_query": {
                            "raw_query": "the phone near the charger",
                            "root": {
                                "categories": ["UNKNOW"],
                                "attributes": [],
                                "spatial_constraints": [
                                    {
                                        "relation": "near",
                                        "anchors": [
                                            {
                                                "categories": ["UNKNOW"],
                                                "attributes": [],
                                                "spatial_constraints": [],
                                                "select_constraint": None,
                                            }
                                        ],
                                    }
                                ],
                                "select_constraint": None,
                            },
                            "expect_unique": True,
                        },
                        "lexical_hints": ["phone", "charger"],
                    },
                    {
                        "kind": "proxy",
                        "rank": 2,
                        "grounding_query": {
                            "raw_query": "proxy: nearby electronic devices",
                            "root": {
                                "categories": ["lamp"],
                                "attributes": [],
                                "spatial_constraints": [],
                                "select_constraint": None,
                            },
                            "expect_unique": True,
                        },
                        "lexical_hints": ["proxy"],
                    },
                    {
                        "kind": "context",
                        "rank": 3,
                        "grounding_query": {
                            "raw_query": "context: desk area",
                            "root": {
                                "categories": ["desk"],
                                "attributes": [],
                                "spatial_constraints": [],
                                "select_constraint": None,
                            },
                            "expect_unique": False,
                        },
                        "lexical_hints": ["context"],
                    },
                ],
            },
            expected_status="context_grounded",
            expected_selected_kind="context",
            expected_matched_objects=[1],
            description="Multi mode - context fallback when both target and anchor unknown",
        )
    )

    # Generate more cases
    scene_configs = [
        ("living", ["sofa", "pillow", "lamp", "door", "rug"]),
        ("bedroom", ["bed", "pillow", "nightstand", "lamp", "dresser"]),
        ("kitchen", ["countertop", "sink", "cabinet", "refrigerator", "microwave"]),
        ("bathroom", ["toilet", "sink", "mirror", "bathtub", "towel"]),
        ("office", ["desk", "chair", "monitor", "keyboard", "bookshelf"]),
    ]

    for i in range(25):
        scene_type, categories = scene_configs[i % 5]
        is_multi = i % 3 == 0

        if is_multi:
            cases.append(
                HypothesisTestCase(
                    case_id=f"exec_gen_{i:03d}",
                    query=f"the unknown_object_{i} in {scene_type}",
                    scene_categories=categories,
                    hypothesis_output={
                        "format_version": "hypothesis_output_v1",
                        "parse_mode": "multi",
                        "hypotheses": [
                            {
                                "kind": "direct",
                                "rank": 1,
                                "grounding_query": {
                                    "raw_query": f"the unknown_object_{i}",
                                    "root": {
                                        "categories": ["UNKNOW"],
                                        "attributes": [],
                                        "spatial_constraints": [],
                                        "select_constraint": None,
                                    },
                                    "expect_unique": True,
                                },
                                "lexical_hints": [],
                            },
                            {
                                "kind": "proxy",
                                "rank": 2,
                                "grounding_query": {
                                    "raw_query": f"proxy for unknown_{i}",
                                    "root": {
                                        "categories": [categories[0]],
                                        "attributes": [],
                                        "spatial_constraints": [],
                                        "select_constraint": None,
                                    },
                                    "expect_unique": True,
                                },
                                "lexical_hints": [],
                            },
                        ],
                    },
                    expected_status="proxy_grounded",
                    expected_selected_kind="proxy",
                    expected_matched_objects=[1],
                    description=f"Generated multi-mode case {i}",
                )
            )
        else:
            cases.append(
                HypothesisTestCase(
                    case_id=f"exec_gen_{i:03d}",
                    query=f"the {categories[0]} in {scene_type}",
                    scene_categories=categories,
                    hypothesis_output={
                        "format_version": "hypothesis_output_v1",
                        "parse_mode": "single",
                        "hypotheses": [
                            {
                                "kind": "direct",
                                "rank": 1,
                                "grounding_query": {
                                    "raw_query": f"the {categories[0]}",
                                    "root": {
                                        "categories": [categories[0]],
                                        "attributes": [],
                                        "spatial_constraints": [],
                                        "select_constraint": None,
                                    },
                                    "expect_unique": True,
                                },
                                "lexical_hints": [categories[0]],
                            }
                        ],
                    },
                    expected_status="direct_grounded",
                    expected_selected_kind="direct",
                    expected_matched_objects=[1],
                    description=f"Generated single-mode case {i}",
                )
            )

    return cases


# ==============================================================================
# Main Generation Functions
# ==============================================================================


def generate_all_ground_truth(output_dir: Path) -> None:
    """Generate all ground truth files."""
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate parsing test cases
    print("Generating parsing test cases...")
    parsing_cases = generate_parsing_test_cases()
    parsing_data = {
        "version": "1.0.0",
        "description": "Query parsing ground truth for migration equivalence testing",
        "scene_categories": SCENE_CATEGORIES,
        "cases": [asdict(case) for case in parsing_cases],
    }
    with open(output_dir / "parsing.json", "w") as f:
        json.dump(parsing_data, f, indent=2)
    print(f"  -> Generated {len(parsing_cases)} parsing test cases")

    # Generate keyframe test cases
    print("Generating keyframe test cases...")
    keyframe_cases = generate_keyframe_test_cases()
    keyframe_data = {
        "version": "1.0.0",
        "description": "Keyframe selection ground truth for migration equivalence testing",
        "cases": [asdict(case) for case in keyframe_cases],
    }
    with open(output_dir / "keyframes.json", "w") as f:
        json.dump(keyframe_data, f, indent=2)
    print(f"  -> Generated {len(keyframe_cases)} keyframe test cases")

    # Generate hypothesis test cases
    print("Generating hypothesis test cases...")
    hypothesis_cases = generate_hypothesis_test_cases()
    hypothesis_data = {
        "version": "1.0.0",
        "description": "Hypothesis execution ground truth for migration equivalence testing",
        "cases": [asdict(case) for case in hypothesis_cases],
    }
    with open(output_dir / "hypotheses.json", "w") as f:
        json.dump(hypothesis_data, f, indent=2)
    print(f"  -> Generated {len(hypothesis_cases)} hypothesis test cases")

    # Generate summary
    summary = {
        "generated_at": "2026-03-22",
        "counts": {
            "parsing": len(parsing_cases),
            "keyframes": len(keyframe_cases),
            "hypotheses": len(hypothesis_cases),
        },
        "files": ["parsing.json", "keyframes.json", "hypotheses.json"],
    }
    with open(output_dir / "manifest.json", "w") as f:
        json.dump(summary, f, indent=2)

    print(f"\nGround truth generation complete!")
    print(f"  Total cases: {sum(summary['counts'].values())}")
    print(f"  Output directory: {output_dir}")


def main() -> None:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate ground truth data for migration equivalence testing"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).parent.parent
        / "tests"
        / "migration"
        / "ground_truth",
        help="Output directory for ground truth files",
    )

    args = parser.parse_args()
    generate_all_ground_truth(args.output_dir)


if __name__ == "__main__":
    main()
